import Head from 'next/head'
import { places, imageCards } from '../data'
import Header from '../components/Header'
import Banner from '../components/Banner'
import LocationCard from '../components/LocationCard'
import ImageCard from '../components/ImageCard'
import LargeCard from '../components/LargeCard'
import Footer from '../components/Footer'

export default function Home() {

  return (
    <div>
      <Head>
        <title>Airbnb Clone</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Header />
      <Banner />

      <main className='max-w-7xl mx-auto px-1 sm:px-8 2xl:px-0'>
        <section className='pt-6'>
          <h2 className='text-3xl sm:text-4xl font-semibold pt-4 pb-8'>Inspiration for your next trip</h2>

          {/* Location Cards */}
          <div className='flex space-x-3 overflow-scroll p-3 -ml-3 scrollbar-hide'>
            {places.map(({img, location, distance}, index) => (
              <LocationCard
                key={index}
                index={index}
                img={img}
                location={location}
                distance={distance}
              />
            ))}
          </div>
        </section>

        <section className='pt-6 pb-6'>
          <h2 className='text-3xl sm:text-4xl font-semibold py-8'>Live Anywhere</h2>
          {/* Image cards */}
          
          <div className='flex space-x-3 overflow-scroll p-3 -ml-3 scrollbar-hide'>
              {imageCards.map(({img, title}, index) => (
                <ImageCard
                  key={index}
                  img={img}
                  title={title}
                />
              ))}
          </div>
        </section>

        <LargeCard 
          img="/images/large_card.webp"
          title="The Greatest Outdoors"
          description="Wishlists curated by Airbnb."
          buttonText="Get Inspired"
        />
      </main>

      <Footer />

    </div>
  )
}

