import Head from 'next/head'
import Header from "../components/Header"
import InfoCard from '../components/InfoCard'
import Map from '../components/Map'
import Footer from '../components/Footer'
import { useRouter } from 'next/router'
import { format } from 'date-fns'
import { posts } from '../data'

const Search = () => {
    const router = useRouter()
    const { location, guests, startDate, endDate } = router.query

    const formattedStartDate = format(new Date(startDate), 'dd MMMM yy')
    const formattedEndDate = format(new Date(endDate), 'dd MMMM yy')
    const range = `${formattedStartDate} - ${formattedEndDate}`

    return (
        <div>
            <Head>
                <title>Search | Airbnb Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" /> 
            </Head>

            <Header placeholder={`${location} | ${range} | ${guests} guests`} />

            <main className='flex'>
                <section className='flex-grow pt-14 px-6'>
                    <p className='text-xs'>300+ Stays - {range} - for {guests} guests</p>
                    <h1 className='text-3xl font-semibold mt-2 mb-6'>Stays in {location}</h1>
                    
                    <div className='hidden lg:inline-flex mb-5 space-x-3 text-gray-800 whitespace-nowrap'>
                        <p className='chip'>Cancellation Flexability</p>
                        <p className='chip'>Type of place</p>
                        <p className='chip'>Price</p>
                        <p className='chip'>Rooms and Beds</p>
                        <p className='chip'>More filters</p>
                    </div>

                    <div>
                        {posts.map(({ img, title, description, location, star, price, total }, index) => (
                            <InfoCard 
                                key={index}
                                img={img}
                                title={title}
                                description={description}
                                location={location}
                                star={star}
                                price={price}
                                total={total}
                            />
                        ))}
                    </div>
                </section>

                <section className='hidden xl:inline-flex xl:min-w-[600px]'>
                    <Map posts={posts} />
                </section>
            </main>

            <Footer />
        </div>
    )
}

export default Search;
